./src/Adder.v
./src/ALU.v
./src/control_E.v
./src/control_M.v
./src/control_W.v
./src/Controller.v
./src/CPU.v
./src/Data_mem.v
./src/SRAM.v
./src/dcache.v
./src/decoder.v
./src/Imme_Ext.v
./src/JB_Unit.v
./src/LD_Filter.v
./src/Mux.v
./src/Mux3.v
./src/Reg_D.v
./src/Reg_E.v
./src/Reg_M.v
./src/Reg_PC.v
./src/Reg_W.v
./src/RegFile.v
./src/Top.v
top_tb.sv
